AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://heitlm-094033154904-eu-west-1/9cc4a3f1ccef9ea76cc8e3928f226686
      Handler: lambda_handler.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      SamResourceId: HelloWorldFunction
